server:
  port: 8780

# HTTP encoding (HttpEncodingProperties)
spring:
  http:
    encoding:
      charset:UTF-8
      enabled:true
      force:true

# MONGODB (MongoProperties)
spring:
  data:
    mongodb:
      host:192.168.99.100
      port:27017
      database:danmu_new

# REDIS (RedisProperties)
spring:
  redis:
    host:192.168.60.239
    port:6380
    #pool:
      #max-idle:8
      #min-idle:0
      #max-active:100
      #max-wait:15000

# FREEMARKER (FreeMarkerAutoConfiguration)
spring:
  freemarker:
    cache:false
    suffix=.ftl
    template-loader-path:classpath:/templates/

# SECURITY (SecurityProperties)
security:
  user:
    name:abc
    password:abc
    role:ADMIN

# HTTP response compression (GzipFilterProperties)
spring:
  http:
    gzip:
      enabled:true

# LOGGING
logging:
  #path:logs
  #file:log.log
  level:
    com.acfun:'DEBUG'
    org.springframework:'WARN'
    org.hibernate:'WARN'
